// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class AttachedComment
{
    public int Id { get; set; }

    public int AttachedCommentId { get; set; }

    public string Comment { get; set; }
}