// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class BillDetail
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string Name { get; set; }

    public string Number { get; set; }

    public string Address { get; set; }

    public string Sn { get; set; }

    public int Amount { get; set; }

    public string ShippingStatus { get; set; }

    public string PaymentStatus { get; set; }

    public int? BounsPoint { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public int? DiscountId { get; set; }

    public virtual ICollection<Collection> Collections { get; set; } = new List<Collection>();

    public virtual Discount Discount { get; set; }

    public virtual Member Member { get; set; }
}