// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class BillDetail
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public decimal FinalPayment { get; set; }

    public int BounsPoint { get; set; }

    public DateTime TransactionDate { get; set; }

    public int? DiscountId { get; set; }

    public virtual ICollection<BillItem> BillItems { get; set; } = new List<BillItem>();

    public virtual ICollection<Collection> Collections { get; set; } = new List<Collection>();

    public virtual Discount Discount { get; set; }

    public virtual Member Member { get; set; }
}