// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class CartItem
{
    public int Id { get; set; }

    public int GameId { get; set; }

    public int CartId { get; set; }

    public decimal Quantity { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual Game Id1 { get; set; }

    public virtual Cart IdNavigation { get; set; }
}