// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class Discount
{
    public int Id { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int Percent { get; set; }

    public string DiscountType { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public string Desciption { get; set; }

    public int? DeveloperId { get; set; }

    public virtual ICollection<BillDetail> BillDetails { get; set; } = new List<BillDetail>();

    public virtual Developer Developer { get; set; }

    public virtual ICollection<DiscountItem> DiscountItems { get; set; } = new List<DiscountItem>();

    public virtual ICollection<WishListe> WishListes { get; set; } = new List<WishListe>();
}