// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class OderDetail
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int GameId { get; set; }

    public int Qty { get; set; }

    public int UnitPrice { get; set; }

    public virtual Order Id1 { get; set; }

    public virtual Game IdNavigation { get; set; }
}