// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RGB.Back.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int BillDetailId { get; set; }

    public int GameId { get; set; }

    public string PaymentMethod { get; set; }

    public bool IsSuccess { get; set; }

    public DateTime PaidAt { get; set; }

    public string Message { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime UpdateAt { get; set; }
}